server:
  port:
    8081
      
spring:
  data:
    mongodb:
      uri:
        mongodb://aviram1989:aviram1989@ds133137.mlab.com:33137/avirampizzeria
        
  application:
    name: PizzaTaskMSMenu
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka 
