server:
  port:
    8083
      
spring:
  data:
    mongodb:
      uri:
        mongodb://aviram1989:aviram1989@ds133137.mlab.com:33137/avirampizzeria?retryWrites=false
        
  application:
    name: PizzaTaskMSDelivery
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka 

pizza:
  delivery:
    appName:
      PizzaTaskDeliveryMS

